
class RowNotFound_Exception(Exception):
    pass